### ISSUE TITLE
bad perf, antialiasing

### ISSUE THREAD

**Issue by zphixon** [zphixon/asteroid#1]
investigate perf issues - Graphics?

investigate adding antialiasing - custom rectangle functions?

**Comment by cheezgi** [comment]
Performance: I'd say that the framerate is so high that the keyboard events are slowing it down. Investigate frame-limiting.

Antialiasing: Great question...

**Comment by cheezgi** [comment]
Still don't really understand the timing issues, but those were fixed by 1d42c6
